# Generated by Django 6.0 on 2026-05-20 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='insurancecontract',
            name='insured_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='core.insuredobject', verbose_name='Объект страхования'),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='position',
            field=models.CharField(choices=[('agent', 'Страховой агент'), ('manager', 'Менеджер'), ('director', 'Директор'), ('accountant', 'Бухгалтер'), ('lawyer', 'Юрист'), ('hr', 'HR-специалист'), ('it', 'IT-специалист'), ('marketing', 'Маркетолог')], max_length=50, verbose_name='Должность'),
        ),
    ]
