# Generated by Django 6.0 on 2026-05-21 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_insurancetype_options_alter_review_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancecontract',
            name='final_payment',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Итоговый платёж с учётом скидки'),
        ),
    ]
