# Generated by Django 6.0 on 2026-05-25 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_insurancecontract_final_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.client', verbose_name='Клиент'),
        ),
    ]
