# Generated by Django 6.0 on 2026-05-20 23:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_staffmember_updated_at_alter_contact_phone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insurancetype',
            options={},
        ),
        migrations.AddField(
            model_name='insurancetype',
            name='tariff_rate',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Тарифная ставка (%)'),
        ),
        migrations.AlterField(
            model_name='insurancecontract',
            name='agent',
            field=models.ForeignKey(limit_choices_to={'position': 'agent'}, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='core.staffmember', verbose_name='Страховой агент'),
        ),
    ]
