# Generated by Django 6.0 on 2026-05-21 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_insurancetype_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insurancetype',
            options={'verbose_name': 'Вид страхования', 'verbose_name_plural': 'Виды страхования'},
        ),
        migrations.AlterField(
            model_name='review',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.client', unique=True, verbose_name='Клиент'),
        ),
    ]
