# Generated by Django 4.2.7 on 2026-09-29 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_review_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='certificate_text',
            field=models.TextField(blank=True, verbose_name='Текст сертификата'),
        ),
        migrations.CreateModel(
            name='HistoryYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('event', models.TextField(verbose_name='Событие')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='core.companyinfo', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Историческое событие',
                'verbose_name_plural': 'История по годам',
                'ordering': ['year'],
            },
        ),
    ]
